

underlay:
    local:
        asn: 60014
    neighbors:
      - interface: xe-0/0/0
        name: SPINE01
        asn: 60001
        peer_ip: 171.0.0.12
        local_ip: 171.0.0.13
      - interface: xe-0/0/1
        name: SPINE02
        asn: 60002
        peer_ip: 171.0.0.14
        local_ip: 171.0.0.15
